
baseURL = "http://example.org/"
languageCode = "en-us"
title = "Rory Dickinson"
theme = "hugo-resume"

[params]
    firstName = "Rory"
    lastName = "Dickinson"
    address = "Fort Worth, TX"
    profileImage = "https://avatars2.githubusercontent.com/u/30642693?s=460&v=4"
    email = "rory.c.dickinson@gmail.com"
    description = "Senior full-stack software developer with consulting experience in Java web application development."
    favicon = "images/favicon.ico"

    # what sections
    showSkills = true
    showProjects = false
    showOpenSource = false
    showPublications = false
    showExperience = true
    showEducation = true
    showCertifications = true
    showArchaeology = true
    showVolunteering = true

    showQr = false

[[params.handles]]
    name = "LinkedIn"
    link = "https://www.linkedin.com/in/taxman2k/"
[[params.handles]]
    name = "GitHub"
    link = "https://github.com/SharkDemon"
[[params.handles]]
    name = "Stack Overflow"
    link = "https://stackoverflow.com/users/10482896/sharkdemon"
    icon = "stack-overflow"
[[params.handles]]
    name = "Hackerrank"
    link = "https://www.hackerrank.com/rory_c_dickinson"
[[params.handles]]
    name = "IMDB"
    link = "https://www.imdb.com/name/nm6010717/"

[params.google.analytics]
    trackerID = "UA-792876-1"

